export const darkThemeValues = {
  '--mb-color-success': '#55b56a',
  '--mb-color-danger': '#f26b5b',
  '--mb-color-warning': '#f0b24d',
  '--mb-color-info': '#66a4ff',
  '--mb-color-primary': '#6ea4ff',
  '--mb-color-positive': '#55b56a',
  '--mb-color-negative': '#f26b5b',
  '--mb-color-investment': '#b18cff',
  '--mb-color-text': '#f3f7fd',
  '--mb-color-neutral': '#b4c1d1',
  '--mb-color-muted': '#8d9aab',
  '--mb-color-disabled': '#647182',
  '--mb-color-background': '#07111f',
  '--mb-color-panel': 'rgba(13, 25, 41, 0.88)',
  '--mb-color-surface': '#101d2d',
  '--mb-color-surface-elevated': '#162538',
  '--mb-color-surface-muted': '#0f1a2a',
  '--mb-color-surface-hover': '#1a2c42',
  '--mb-color-surface-selected': '#1c3860',
  '--mb-color-border': 'rgba(151, 177, 210, 0.16)',
  '--mb-color-border-strong': 'rgba(162, 189, 223, 0.3)',
  '--mb-color-border-input': 'rgba(154, 180, 212, 0.24)',
  '--mb-space-xs': '4px',
  '--mb-space-sm': '8px',
  '--mb-space-md': '16px',
  '--mb-space-lg': '24px',
  '--mb-space-xl': '32px',
  '--mb-space-xxl': '48px',
  '--mb-font-size-xs': '12px',
  '--mb-font-size-sm': '14px',
  '--mb-font-size-md': '16px',
  '--mb-font-size-lg': '18px',
  '--mb-font-size-xl': '20px',
  '--mb-font-weight-normal': '400',
  '--mb-font-weight-medium': '500',
  '--mb-font-weight-bold': '700',
  '--mb-border-width': '1px',
  '--mb-border-width-thick': '2px',
  '--mb-border-style': 'solid',
  '--mb-shadow-sm': '0 12px 30px rgba(1, 7, 16, 0.28)',
  '--mb-shadow-md': '0 20px 56px rgba(1, 7, 16, 0.4)',
  '--mb-shadow-lg': '0 36px 80px rgba(1, 7, 16, 0.52)',
  '--mb-radius-sm': '4px',
  '--mb-radius-md': '10px',
  '--mb-radius-lg': '16px',
  '--mb-radius-xl': '22px',
  '--mb-chart-color-income': '#55b56a',
  '--mb-chart-color-expense': '#f26b5b',
  '--mb-chart-color-transfer': '#6ea4ff',
  '--mb-chart-color-investment': '#b18cff',
  '--mb-chart-color-refund': '#f0b24d',
  '--mb-chart-color-cash': '#6ea4ff',
  '--mb-chart-color-non-cash': '#4ab9af',
  '--mb-chart-color-operating': '#55b56a',
  '--mb-chart-color-investing': '#6ea4ff',
  '--mb-chart-color-financing': '#f0b24d',
  '--mb-chart-color-primary': '#6ea4ff',
  '--mb-chart-color-secondary': '#55b56a',
  '--mb-chart-color-tertiary': '#f0b24d',
  '--mb-chart-color-quaternary': '#b18cff',
} as const

export type DarkThemeValues = typeof darkThemeValues
