export const lightThemeValues = {
  '--mb-color-success': '#2b8a3e',
  '--mb-color-danger': '#c43d2f',
  '--mb-color-warning': '#d0881b',
  '--mb-color-info': '#2f7cf6',
  '--mb-color-primary': '#1e63da',
  '--mb-color-positive': '#2b8a3e',
  '--mb-color-negative': '#c43d2f',
  '--mb-color-investment': '#8f5bd6',
  '--mb-color-text': '#132238',
  '--mb-color-neutral': '#506176',
  '--mb-color-muted': '#7f8c9d',
  '--mb-color-disabled': '#a5b1bf',
  '--mb-color-background': '#edf3fb',
  '--mb-color-panel': 'rgba(255, 255, 255, 0.78)',
  '--mb-color-surface': '#ffffff',
  '--mb-color-surface-elevated': '#ffffff',
  '--mb-color-surface-muted': '#f4f7fb',
  '--mb-color-surface-hover': '#ebf1f8',
  '--mb-color-surface-selected': '#dfeafe',
  '--mb-color-border': 'rgba(135, 154, 176, 0.22)',
  '--mb-color-border-strong': 'rgba(96, 118, 142, 0.4)',
  '--mb-color-border-input': 'rgba(112, 130, 151, 0.34)',
  '--mb-space-xs': '4px',
  '--mb-space-sm': '8px',
  '--mb-space-md': '16px',
  '--mb-space-lg': '24px',
  '--mb-space-xl': '32px',
  '--mb-space-xxl': '48px',
  '--mb-font-size-xs': '12px',
  '--mb-font-size-sm': '14px',
  '--mb-font-size-md': '16px',
  '--mb-font-size-lg': '18px',
  '--mb-font-size-xl': '20px',
  '--mb-font-weight-normal': '400',
  '--mb-font-weight-medium': '500',
  '--mb-font-weight-bold': '700',
  '--mb-border-width': '1px',
  '--mb-border-width-thick': '2px',
  '--mb-border-style': 'solid',
  '--mb-shadow-sm': '0 10px 24px rgba(18, 38, 63, 0.06)',
  '--mb-shadow-md': '0 20px 50px rgba(25, 47, 73, 0.1)',
  '--mb-shadow-lg': '0 30px 70px rgba(15, 31, 53, 0.14)',
  '--mb-radius-sm': '4px',
  '--mb-radius-md': '10px',
  '--mb-radius-lg': '16px',
  '--mb-radius-xl': '22px',
  '--mb-chart-color-income': '#2b8a3e',
  '--mb-chart-color-expense': '#d84f3d',
  '--mb-chart-color-transfer': '#1e63da',
  '--mb-chart-color-investment': '#8f5bd6',
  '--mb-chart-color-refund': '#cc8a2d',
  '--mb-chart-color-cash': '#3c7adf',
  '--mb-chart-color-non-cash': '#2f9e94',
  '--mb-chart-color-operating': '#2b8a3e',
  '--mb-chart-color-investing': '#1e63da',
  '--mb-chart-color-financing': '#cc8a2d',
  '--mb-chart-color-primary': '#1e63da',
  '--mb-chart-color-secondary': '#2b8a3e',
  '--mb-chart-color-tertiary': '#cc8a2d',
  '--mb-chart-color-quaternary': '#8f5bd6',
} as const

export type LightThemeValues = typeof lightThemeValues
